website:
  dynaconf_merge: true
  name: "website"
  llm_model: "gemini/gemini-3-flash-preview"
  embedding_model: "gemini/text-embedding-004"
  digest:
    top: 100
    hours: 96 # 24 * 4
  summarise:
    prev_file_prefix: "deduped"
    save_to_supabase: true
    prompt: "summarisation"
    table_name: "raw_articles"
    max_concurrent: 5
    model: "@format {this.llm_model}"
  dedup:
    model: "@format {this.embedding_model}"
  collect:
    model: "@format {this.llm_model}"
    min_score: 8.0
    min_novelty_score: 2.0
    filter_mode: "AND"
  publish:
    slack: true
    slack_days: [1,2,3,4,5,6,7]  # 1=Monday, 7=Sunday
    linkedin: true
    linkedin_days: [1, 5]  # 1=Monday

website-local:
  dynaconf_merge: true
  name: "website"
  llm_model: "gemini/gemini-3-flash-preview"
  embedding_model: "gemini/text-embedding-004"
  summarise:
    prev_file_prefix: "deduped"
    prompt: "summarisation"
    save_to_supabase: false
    max_concurrent: 5
    model: "@format {this.llm_model}"
  dedup:
    model: "@format {this.embedding_model}"
  collect:
    model: "@format {this.llm_model}"
    min_score: 8.0
    min_novelty_score: 2.0
    filter_mode: "AND"
  digest:
    top: 100
    hours: 24
  publish:
    slack: false
    slack_days: [1,2,3,4,5,6,7]
    linkedin: false
    linkedin_days: [1]

mountainmap:
  name: "mountainmap"
  llm_model: "gemini/gemini-3-flash-preview"
  embedding_model: "gemini/text-embedding-004"
  digest:
    top: 100
    hours: 168
  summarise:
    prev_file_prefix: "digest"
    prompt: "summarise_enrich"
    save_to_supabase: true
    max_concurrent: 3
    table_name: "raw_post_mountainmap"
    model: "@format {this.llm_model}"
  dedup:
    model: "@format {this.embedding_model}"

mountainmap-local:
  name: "mountainmap"
  llm_model: "gemini/gemini-3-flash-preview"
  embedding_model: "gemini/text-embedding-004"
  digest:
    top: 5
    hours: 24
  summarise:
    prev_file_prefix: "digest"
    prompt: "summarise_enrich"
    save_to_supabase: false
    max_concurrent: 3
    model: "@format {this.llm_model}"
  dedup:
    model: "@format {this.embedding_model}"
